# Generated by Django 6.0 on 2026-01-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'familias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('MATERIA', 'Materia Prima'), ('PRODUCTO', 'Producto Final')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo de Producto',
                'verbose_name_plural': 'Modelos de Producto',
                'db_table': 'modelos_producto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código automático')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Descripción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('M', 'Metros'), ('M2', 'Metros cuadrados'), ('M3', 'Metros cúbicos'), ('L', 'Litros'), ('UN', 'Unidades')], default='KG', max_length=20, verbose_name='Unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock mínimo')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('activo', models.BooleanField(default=True)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.familia', verbose_name='Familia')),
                ('modelo', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MATERIA'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.modeloproducto', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'db_table': 'materias_primas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código automático')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Descripción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.IntegerField(verbose_name='Stock mínimo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('tiempo_fabricacion', models.IntegerField(default=0, help_text='Tiempo en horas', verbose_name='Tiempo de fabricación')),
                ('activo', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PRODUCTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.modeloproducto', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['codigo'],
            },
        ),
    ]
